feat: update notebook server images (#7647)
* feat: update example notebook images

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Remove incorrect flow-chart png

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Update `kfp` python package to `2.9.0`

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Allow RStudio image to start outside Kubernetes

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Put note about why RStudio has WARN log-level

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Allow users to specify their own Reticulate python

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Fix installing packages on RStudio

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

* Add `r-shiny` to base RStudio image

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

---------

Signed-off-by: Mathew Wicks <5735406+thesuperzapper@users.noreply.github.com>

diff --git a/components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix b/components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix
--- a/components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix
+++ b/components/example-notebook-servers/rstudio/s6/cont-init.d/02-rstudio-env-fix
@@ -1,5 +1,7 @@
 #!/command/with-contenv bash
 
-# rstudio terminal cant see environment variables set by the container runtime
-# (which breaks kubectl, to fix this we store the KUBERNETES_* env vars in Renviron.site)
-env | grep KUBERNETES_ >> ${R_HOME}/etc/Renviron.site
+# rstudio terminal cant see environment variables set by the container runtime,
+# this breaks kubectl, so we store the KUBERNETES_* env vars in Renviron.site
+# NOTE: the `|| true` is needed because `grep` will exit with non-zero status for no matches
+echo "INFO: adding KUBERNETES_* env vars to '${R_HOME}/etc/Renviron.site'..."
+env | grep KUBERNETES_ >> "${R_HOME}/etc/Renviron.site" || true
